# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

print ('@@@@@  @      @  @@     @       @')
print ('    @  @      @  @ @    @      @ @')
print ('    @  @      @  @  @   @     @   @')
print ('    @  @      @  @   @  @    @@@@@@@')
print ('   @   @      @  @    @ @   @       @')
print ('  @      @@@@    @     @@  @         @')
def GLBB():
    #dibawah ini adalah input datanya
    v0 = int(input("Masukan v0: "))
    t  = int(input("Masukan t: "))
    a  = int(input("Masukan a: "))

    #dibawah ini adalah rumus nya
    s = v0 * t + (1/2) * a * t**2

    print("Diketahui:")
    print("Jarak tempuh jika kecepatan awal = ", v0)
    print("Waktu = ", t)
    print("Percepatan = ", a)
    print("Maka jarak tempuh nya adalah = ", s)
GLBB()

import math

def luas_kubus(sisi):
    return 6 * sisi ** 2

def luas_balok(panjang, lebar, tinggi):
    return 2 * (panjang * lebar + panjang * tinggi + lebar * tinggi)

def luas_tabung(jari_jari, tinggi):
    luas_alas = math.pi * jari_jari ** 2
    luas_permukaan = 2 * math.pi * jari_jari * (jari_jari + tinggi)
    return luas_alas + luas_permukaan

def luas_kerucut(jari_jari, tinggi):
    s = math.sqrt(jari_jari ** 2 + tinggi ** 2)
    luas_alas = math.pi * jari_jari ** 2
    luas_permukaan = math.pi * jari_jari * s
    return luas_alas + luas_permukaan

def luas_bola(jari_jari):
    return 4 * math.pi * jari_jari ** 2

print("Pilih jenis bangun ruang:")
print()

print("1. Kubus")
print()

print("2. Balok")
print()

print("3. Tabung")
print()

print("4. Kerucut")
print()

print("5. Bola")
print()

pilihan = int(input("Masukkan nomor pilihan (1/2/3/4/5): "))
print()

if pilihan == 1:
    sisi = float(input("Masukkan panjang sisi kubus: "))
    luas = luas_kubus(sisi)
elif pilihan == 2:
    panjang = float(input("Masukkan panjang balok: "))
    lebar = float(input("Masukkan lebar balok: "))
    tinggi = float(input("Masukkan tinggi balok: "))
    luas = luas_balok(panjang, lebar, tinggi)
elif pilihan == 3:
    jari_jari = float(input("Masukkan jari-jari tabung: "))
    tinggi = float(input("Masukkan tinggi tabung: "))
    luas = luas_tabung(jari_jari, tinggi)
elif pilihan == 4:
    jari_jari = float(input("Masukkan jari-jari kerucut: "))
    tinggi = float(input("Masukkan tinggi kerucut: "))
    luas = luas_kerucut(jari_jari, tinggi)
elif pilihan == 5:
    jari_jari = float(input("Masukkan jari-jari bola: "))
    luas = luas_bola(jari_jari)
else:
    print("Pilihan tidak valid")
    luas = None

if luas is not None:
    print("Luas permukaan adalah:", luas)